theme = "slick"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 50.0

[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%y %R"

[[block]]
block = "sound"
format = "{output_name} {volume}"
driver = "pulseaudio"
[block.mappings]
"alsa_output.pci-0000_0a_00.4.analog-stereo" = "🔈"
"alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo" = "🎧"
